---
name: AdvancedJobs
api:
- 3.11.4
- 3.17.0
author: LousWiteMC
version: "0.3"
main: LousWiteMC\AdvancedJobs\AdvancedJobs
commands:
  job:
    usage: /job
    description: Open Jobs Manager
...
